#include "pds/config/PixisConfigType.hh"

void Pds::PixisConfig::setNumIntegrationShots(PixisConfigType& c,
                                        unsigned n)
{
  new(&c) PixisConfigType(c.width(),
                          c.height(),
                          c.orgX(),
                          c.orgY(),
                          c.binX(),
                          c.binY(),
                          c.exposureTime(),
                          c.coolingTemp(),
                          c.readoutSpeed(),
                          c.gainMode(),
                          c.adcMode(),
                          c.triggerMode(),
                          c.activeWidth(),
                          c.activeHeight(),
                          c.activeTopMargin(),
                          c.activeBottomMargin(),
                          c.activeLeftMargin(),
                          c.activeRightMargin(),
                          c.cleanCycleCount(),
                          c.cleanCycleHeight(),
                          c.cleanFinalHeight(),
                          c.cleanFinalHeightCount(),
                          c.maskedHeight(),
                          c.kineticHeight(),
                          c.vsSpeed(),
                          c.infoReportInterval(),
                          c.exposureEventCode(),
                          n);
}

void Pds::PixisConfig::setSize(PixisConfigType& c,
                               unsigned w,
                               unsigned h)
{
  new(&c) PixisConfigType(w, h,
                          c.orgX(),
                          c.orgY(),
                          c.binX(),
                          c.binY(),
                          c.exposureTime(),
                          c.coolingTemp(),
                          c.readoutSpeed(),
                          c.gainMode(),
                          c.adcMode(),
                          c.triggerMode(),
                          c.activeWidth(),
                          c.activeHeight(),
                          c.activeTopMargin(),
                          c.activeBottomMargin(),
                          c.activeLeftMargin(),
                          c.activeRightMargin(),
                          c.cleanCycleCount(),
                          c.cleanCycleHeight(),
                          c.cleanFinalHeight(),
                          c.cleanFinalHeightCount(),
                          c.maskedHeight(),
                          c.kineticHeight(),
                          c.vsSpeed(),
                          c.infoReportInterval(),
                          c.exposureEventCode(),
                          c.numIntegrationShots());
}
