#include "pds/config/VimbaConfigType.hh"

void Pds::VimbaConfig::setROI(AlviumConfigType& c,
                              uint32_t x,
                              uint32_t y,
                              uint32_t w,
                              uint32_t h)
{
  new(&c) AlviumConfigType(c.reverseX(),
                           c.reverseY(),
                           c.contrastEnable(),
                           c.correctionEnable(),
                           c.roiEnable(),
                           c.correctionType(),
                           c.correctionSet(),
                           c.pixelMode(),
                           c.triggerMode(),
                           w,
                           h,
                           x,
                           y,
                           c.sensorWidth(),
                           c.sensorHeight(),
                           c.contrastDarkLimit(),
                           c.contrastBrightLimit(),
                           c.contrastShape(),
                           c.exposureTime(),
                           c.blackLevel(),
                           c.gain(),
                           c.gamma(),
                           c.manufacturer(),
                           c.family(),
                           c.model(),
                           c.manufacturerId(),
                           c.version(),
                           c.serialNumber(),
                           c.firmwareId(),
                           c.firmwareVersion());
}

void Pds::VimbaConfig::setSensorInfo(AlviumConfigType& c,
                                     uint32_t w,
                                     uint32_t h)
{
  new(&c) AlviumConfigType(c.reverseX(),
                           c.reverseY(),
                           c.contrastEnable(),
                           c.correctionEnable(),
                           c.roiEnable(),
                           c.correctionType(),
                           c.correctionSet(),
                           c.pixelMode(),
                           c.triggerMode(),
                           c.width(),
                           c.height(),
                           c.offsetX(),
                           c.offsetY(),
                           w,
                           h,
                           c.contrastDarkLimit(),
                           c.contrastBrightLimit(),
                           c.contrastShape(),
                           c.exposureTime(),
                           c.blackLevel(),
                           c.gain(),
                           c.gamma(),
                           c.manufacturer(),
                           c.family(),
                           c.model(),
                           c.manufacturerId(),
                           c.version(),
                           c.serialNumber(),
                           c.firmwareId(),
                           c.firmwareVersion());
}

void Pds::VimbaConfig::setDeviceInfo(AlviumConfigType& c,
                                     const char* manufacturer,
                                     const char* family,
                                     const char* model,
                                     const char* manufacturerId,
                                     const char* version,
                                     const char* serialNumber,
                                     const char* firmwareId,
                                     const char* firmwareVersion)
{
  new(&c) AlviumConfigType(c.reverseX(),
                           c.reverseY(),
                           c.contrastEnable(),
                           c.correctionEnable(),
                           c.roiEnable(),
                           c.correctionType(),
                           c.correctionSet(),
                           c.pixelMode(),
                           c.triggerMode(),
                           c.width(),
                           c.height(),
                           c.offsetX(),
                           c.offsetY(),
                           c.sensorWidth(),
                           c.sensorHeight(),
                           c.contrastDarkLimit(),
                           c.contrastBrightLimit(),
                           c.contrastShape(),
                           c.exposureTime(),
                           c.blackLevel(),
                           c.gain(),
                           c.gamma(),
                           manufacturer,
                           family,
                           model,
                           manufacturerId,
                           version,
                           serialNumber,
                           firmwareId,
                           firmwareVersion);  
}
